name: Afterlife
main: atom\afterlife\Main
version: 3.2.10
api: 
  - 3.5.5

author: Atom

commands:
  profile:
    description: "Shows PvP Stats"
  stats:
    description: "Shows PvP Stats"
  setleaderboard: 
    description: sets leader board that displays player stats
    
permissions:
  afterlife.admin:
    default: op
    description: give permission to run command
